# Generated by Django 4.2 on 2023-10-06 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_executivebody_image_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="date",
            new_name="end_date",
        ),
        migrations.AddField(
            model_name="event",
            name="mode",
            field=models.CharField(default="Online", max_length=50),
        ),
        migrations.AddField(
            model_name="event",
            name="prize_money",
            field=models.CharField(default="No Prize", max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="team_size",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
