# Generated by Django 4.2 on 2023-10-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_event_end_time_event_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image_url",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="executivebody",
            name="image_url",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="faculty",
            name="image_url",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="operatingbody",
            name="image_url",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
